### ISSUE TITLE
Wrong Values?

### ISSUE THREAD

**Issue by ziadkiwan** [A3tra3rpi/G933-battery-information-for-linux#1]
Hello, today i was testing your script thanks for making it!
OS: ubuntu 19.10
When i run it:
sudo python3 g933battery.py 
Battery:~101% (estimated from:3/2,12/255) Status: Idle

if you want to investigate we can have an anydesk session so you can check!

**Comment by A3tra3rpi** [comment]
Thanks for trying it out. After making this script I found better way to get the charge: github.com/Sapd/HeadsetControl. But if you still want to use this script, this is how the Sapds code calculated the charge writen to python and adapted to work in this script. This seems to return more accurate values: 
`def get_battery_level(b1, b2):
    #GOT THIS FORMULA FROM https://github.com/Sapd/HeadsetControl
    voltage = (b1 << 8) | b2;
    return int(round(estimate_battery_level(voltage)))

#FUNCTION FROM https://github.com/Sapd/HeadsetControl
#From C to Python
def estimate_battery_level(voltage):
    if (voltage <= 3525):
        return float((0.03 * voltage) - 101)
    if (voltage > 4030):
        return float(100.0)
    # f(x)=3.7268473047*10^(-9)x^(4)-0.00005605626214573775*x^(3)+0.3156051902814949*x^(2)-788.0937250298629*x+736315.3077118985
    return float(0.0000000037268473047 * pow(voltage, 4) - 0.00005605626214573775 * pow(voltage, 3) + 0.3156051902814949 * pow(voltage, 2) - 788.0937250298629 * voltage + 736315.3077118985)`

**Comment by ziadkiwan** [comment]
I see. yes I found headsetcontrol quite a good one!, but i'm facing problems with it too for some strange reasons!
